export const config = {
    MSUsuariosUrls: {
        baseUrl: 'http://localhost:3004',
        login: '/usuario/login',
        register: '/usuario/register',
        registerEmpleado: '/usuario/register/empleado',
        refreshToken: '/usuario/refresh-token',
        getDatosCliente: '/usuario/datos-cliente',
        getDatosEmpleadoById: (id: number) => `/usuario/datos-empleado/${id}`,
        verificarExistenciaTipoClienteById: (id: number) =>
            `/tipo-cliente/validar-existencia/${id}`,
        findUserByEmail: (email: string) => `/usuario/find-by-email/${email}`
    },
    MSFuncionesUrls: {
        baseUrl: 'http://localhost:3003',
        getDisponibilidadByFuncionId: (id: number) =>
            `/funcion/${id}/butacas-detalle`,
        getFuncionesByPeliculaId: (id: number) =>
            `/funcion/funciones-por-pelicula/${id}`,
        getFuncionById: (id: number) => `/funcion/${id}`,
    },
    MSPeliculasUrls: {
        baseUrl: 'http://localhost:3001',
        registrarPelicula: '/pelicula/new',
        actualizarPeliculaById: (id: number) => `/pelicula/${id}`,
        getAllPeliculas: '/pelicula',
        getPeliculaById: (id: number) => `/pelicula/${id}`,
        deletePeliculaById: (id: number) => `/pelicula/${id}`,
        registrarGenero: '/genero',
        actualizarGeneroById: (id: number) => `/genero/${id}`,
        getAllGeneros: '/genero',
        getGeneroById: (id: number) => `/genero/${id}`,
        deleteGeneroById: (id: number) => `/genero/${id}`,
        registrarIdioma: '/idioma',
        actualizarIdiomaById: (id: number) => `/idioma/${id}`,
        getAllIdiomas: '/idioma',
        getIdiomaById: (id: number) => `/idioma/${id}`,
        registrarClasificacion: '/clasificacion',
        actualizarClasificacionById: (id: number) => `/clasificacion/${id}`,
        getAllClasificaciones: '/clasificacion',
        getClasificacionById: (id: number) => `/clasificacion/${id}`,
        deleteClasificacionById: (id: number) => `/clasificacion/${id}`,
        registrarEstadoPelicula: '/estado-pelicula',
        actualizarEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        getAllEstadosPelicula: '/estado-pelicula',
        getEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        deleteEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        registrarTipoPelicula: '/tipo-pelicula',
        actualizarTipoPeliculaById: (id: number) => `/tipo-pelicula/${id}`,
        getAllTiposPelicula: '/tipo-pelicula',
        registrarFormato: '/formato',
        actualizarFormatoById: (id: number) => `/formato/${id}`,
        getAllFormatos: '/formato',
        registrarSala: '/sala',
        actualizarSalaById: (id: number) => `/sala/${id}`,
        getAllSalas: '/sala',
        registrarFuncion: '/funcion',
        actualizarFuncionById: (id: number) => `/funcion/${id}`,
        getAllFunciones: '/funcion',
        registrarFila: '/fila',
        actualizarFilaById: (id: number) => `/fila/${id}`,
        getAllFilas: '/fila',
        registrarButaca: '/butaca',
        actualizarButacaById: (id: number) => `/butaca/${id}`,
        getAllButacas: '/butaca',
    },
    MSVentasUrls: {
        baseUrl: 'http://localhost:3003',
        iniciarProcesoPago: '/ventas/proceso-pago',
    },
    MSPromocionesUrls: {
        baseUrl: 'http://localhost:3004',
        registrarPromocion: '/promocion/new',
        actualizarPromocionById: (id: number) => `/promocion/${id}`,
        getAllPromociones: '/promocion',
        getPromocionById: (id: number) => `/promocion/${id}`,
        deletePromocionById: (id: number) => `/promocion/${id}`,
        registrarDia: '/dia/new',
        actualizarDiaById: (id: number) => `/dia/${id}`,
        getAllDias: '/dia',
        getDiaById: (id: number) => `/dia/${id}`,
        deleteDiaById: (id: number) => `/dia/${id}`,
        verificarPromocionById: (id: number) =>
            `/promocion/verificar-promocion/${id}`,
    },
};
