export const config = {
    MSUsuariosUrls: {
        baseUrl: 'http://localhost:3004',
        login: '/usuario/login',
        register: '/usuario/register',
        registerEmpleado: '/usuario/register/empleado',
        refreshToken: '/usuario/refresh-token',
        getDatosCliente: '/usuario/datos-cliente',
        getDatosEmpleadoById: (id: number) => `/usuario/datos-empleado/${id}`,
        verificarExistenciaTipoClienteById: (id: number) =>
            `/tipo-cliente/validar-existencia/${id}`,
        findUserByEmail: (email: string) => `/usuario/find-by-email/${email}`,
        GetTipoClienteById: (id: number) => `/tipo-cliente/admin/${id}`,
        CreateTipoCliente: '/tipo-cliente/admin/new',
        UpdateTipoCliente: (id: number) => `/tipo-cliente/admin/${id}`,
        DeleteTipoCliente: (id: number) => `/tipo-cliente/admin/${id}`,
        GetAllTipoClientes: () => `/tipo-cliente/admin/all`,
        CreateRole: '/roles/admin/create',
        CreatePermission: '/permissions/admin/create',
        GetAllRoles: () => '/roles/admin/all',
        GetAllPermissions: () => '/permissions/admin/all',
    },
    MSFuncionesUrls: {
        baseUrl: 'http://localhost:3003',
        getDisponibilidadByFuncionId: (id: number) =>
            `/funcion/${id}/butacas-detalle`,
        getFuncionesByPeliculaId: (id: number) =>
            `/funcion/funciones-por-pelicula/${id}`,
        getFuncionById: (id: number) => `/funcion/${id}`,
        getFunciones: () => `/funcion/admin/all`,
        deleteFuncion: (id: number) => `/funcion/admin/${id}`,
        createFuncion: '/funcion/admin/new',
        updateFuncion: (id: number) => `/funcion/admin/${id}`,

        registrarButaca: '/butaca',
        actualizarButacaById: (id: number) => `/butaca/${id}`,
        getAllButacas: '/butaca',
        getAllDisponibilidadButaca: '/disponibilidad-butaca',
        getDisponibilidadButacaById: (id: number) =>
            `/disponibilidad-butaca/${id}`,
        updateDisponibilidadButacaById: (id: number) =>
            `/disponibilidad-butaca/${id}`,
        reservarDisponibilidadButaca: '/disponibilidad-butaca/reservar',
        ocuparDisponibilidadButaca: '/disponibilidad-butaca/ocupar',
        registrarEstadoDisponibilidadButaca: '/estado-disponibilidad-butaca',
        getAllEstadosDisponibilidadButaca: '/estado-disponibilidad-butaca',
        getEstadoDisponibilidadButacaById: (id: number) =>
            `/estado-disponibilidad-butaca/${id}`,
        actualizarEstadoDisponibilidadButacaById: (id: number) =>
            `/estado-disponibilidad-butaca/${id}`,
        registrarFila: '/fila',
        actualizarFilaById: (id: number) => `/fila/${id}`,
        getAllFilas: '/fila',
        registrarFormato: '/formato/admin/new',
        actualizarFormatoById: (id: number) => `/formato/admin/${id}`,
        getAllFormatos: '/formato',
        getAllFormatosAdmin: '/formato/admin/all',
        getFormatoAdminById: (id: number) => `/formato/admin/${id}`,
        getFormatoForPut: (id: number) => `/formato/${id}/admin`,
        registrarIdioma: '/idioma/admin/new',
        getAllIdiomas: '/idioma/admin/all',
        getIdiomaById: (id: number) => `/idioma/admin/${id}`,
        actualizarIdiomaById: (id: number) => `/idioma/admin/${id}`,
        actualizarIdiomaParcialById: (id: number) => `/idioma/${id}`,
        registrarSala: '/salas/admin/new',
        actualizarSalaById: (id: number) => `/salas/admin/${id}`,
        getAllSalas: '/salas',
        getAllSalasAdmin: '/salas/admin/all',
        getSalasForSelect: '/salas/admin/selec',
    },
    MSPeliculasUrls: {
        baseUrl: 'http://localhost:3001',
        registrarPelicula: '/pelicula/new',
        actualizarPeliculaById: (id: number) => `/pelicula/${id}`,
        getAllPeliculas: '/pelicula',
        getPeliculaById: (id: number) => `/pelicula/${id}`,
        deletePeliculaById: (id: number) => `/pelicula/${id}`,
        registrarGenero: '/genero/admin/new',
        actualizarGeneroById: (id: number) => `/genero/${id}`,
        getAllGeneros: '/genero',
        getGeneroById: (id: number) => `/genero/${id}`,
        deleteGeneroById: (id: number) => `/genero/${id}`,
        registrarIdioma: '/idioma/admin/new',
        actualizarIdiomaById: (id: number) => `/idioma/${id}`,
        getAllIdiomas: '/idioma',
        getIdiomaById: (id: number) => `/idioma/${id}`,
        registrarClasificacion: '/clasificacion/admin/new',
        actualizarClasificacionById: (id: number) => `/clasificacion/${id}`,
        getAllClasificaciones: '/clasificacion',
        getClasificacionById: (id: number) => `/clasificacion/${id}`,
        deleteClasificacionById: (id: number) => `/clasificacion/admin/${id}`,
        registrarEstadoPelicula: '/estado-pelicula',
        actualizarEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        getAllEstadosPelicula: '/estado-pelicula',
        getEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        deleteEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        registrarTipoPelicula: '/tipo-pelicula',
        actualizarTipoPeliculaById: (id: number) => `/tipo-pelicula/${id}`,
        getAllTiposPelicula: '/tipo-pelicula',
        registrarFormato: '/formato',
        actualizarFormatoById: (id: number) => `/formato/${id}`,
        getAllFormatos: '/formato',
        registrarSala: '/sala',
        actualizarSalaById: (id: number) => `/sala/${id}`,
        getAllSalas: '/sala',
        registrarFuncion: '/funcion',
        actualizarFuncionById: (id: number) => `/funcion/${id}`,
        getAllFunciones: '/funcion',
        registrarFila: '/fila',
        actualizarFilaById: (id: number) => `/fila/${id}`,
        getAllFilas: '/fila',
        registrarButaca: '/butaca',
        actualizarButacaById: (id: number) => `/butaca/${id}`,
        getAllButacas: '/butaca',
    },
    MSVentasUrls: {
        baseUrl: 'http://localhost:3002',
        iniciarProcesoPago: '/venta/proceso-pago',
        getHorariosMasElegidos:
            '/venta/admin/reportes/horarios-mas-elegidos/actual',
        getEntradasPorDiaSemanaMesActual:
            '/venta/admin/reportes/entradas-por-dia-semana/actual',
        getPeliculasPorRangoVentasTrimestral:
            '/venta/admin/reportes/peliculas-rango-ventas/trimestral',
        findAllVentas: '/venta/admin/all',
        crearEstadoVenta: '/estado-venta/admin/new',
        findAllEstadoVenta: '/estado-venta/admin/all',
        getEstadoVentaById: (id: number) => `/estado-venta/admin/${id}`,
        eliminarEstadoVenta: (id: number) => `/estado-venta/admin/${id}`,
        crearEntradaPorDisponibilidadIds: '/entrada',
        abrirVenta: '/venta/abrir-venta',
        cerrarVenta: (id: number) => `/venta/cerrar-venta/${id}`,
    },
    MSPromocionesUrls: {
        baseUrl: 'http://localhost:3004',
        registrarPromocion: '/promocion/admin/new',
        actualizarPromocionById: (id: number) => `/promocion/admin/${id}`,
        getAllPromociones: '/promocion/admin/all',
        getPromocionById: (id: number) => `/promocion/admin/${id}`,
        deletePromocionById: (id: number) => `/promocion/admin/${id}`,
        registrarDia: '/dia/new',
        actualizarDiaById: (id: number) => `/dia/admin/${id}`,
        getAllDias: '/dia/admin/all',
        getDiaById: (id: number) => `/dia/admin/${id}`,
        deleteDiaById: (id: number) => `/dia/admin/${id}`,
        verificarPromocionById: (id: number) =>
            `/promocion/verificar-promocion/${id}`,
    },
};
