export const config = {
    MSUsuariosUrls: {
        baseUrl: 'http://localhost:3000',
        login: '/usuarios/login',
        register: '/usuarios/register',
        registerEmpleado: '/usuarios/register/empleado',
        refreshToken: '/usuarios/refresh-token',
        getDatosClienteById: (id: number) => `/usuarios/datos-cliente/${id}`,
        getDatosEmpleadoById: (id: number) => `/usuarios/datos-empleado/${id}`,
        verificarExistenciaTipoClienteById: (id: number) =>
            `/tipo-cliente/validar-existencia/${id}`,
    },
    MSFuncionesUrls: {
        baseUrl: 'http://localhost:3001',
        getDisponibilidadByFuncionId: (id: number) =>
            `/funciones/butaca-por-funcion/${id}`,
    },
    MSPeliculasUrls: {
        baseUrl: 'http://localhost:3002',
        getFuncionesByPeliculaId: (id: number) => `/pelicula/funciones/${id}`,
        registrarPelicula: '/pelicula',
        actualizarPeliculaById: (id: number) => `/pelicula/${id}`,
        getAllPeliculas: '/pelicula',
        getPeliculaById: (id: number) => `/pelicula/${id}`,
        registrarGenero: '/genero',
        actualizarGeneroById: (id: number) => `/genero/${id}`,
        getAllGeneros: '/genero',
        registrarIdioma: '/idioma',
        actualizarIdiomaById: (id: number) => `/idioma/${id}`,
        getAllIdiomas: '/idioma',
        registrarClasificacion: '/clasificacion',
        actualizarClasificacionById: (id: number) => `/clasificacion/${id}`,
        getAllClasificaciones: '/clasificacion',
        registrarEstadoPelicula: '/estado-pelicula',
        actualizarEstadoPeliculaById: (id: number) => `/estado-pelicula/${id}`,
        getAllEstadosPelicula: '/estado-pelicula',
        registrarTipoPelicula: '/tipo-pelicula',
        actualizarTipoPeliculaById: (id: number) => `/tipo-pelicula/${id}`,
        getAllTiposPelicula: '/tipo-pelicula',
        registrarFormato: '/formato',
        actualizarFormatoById: (id: number) => `/formato/${id}`,
        getAllFormatos: '/formato',
        registrarSala: '/sala',
        actualizarSalaById: (id: number) => `/sala/${id}`,
        getAllSalas: '/sala',
        registrarFuncion: '/funcion',
        actualizarFuncionById: (id: number) => `/funcion/${id}`,
        getAllFunciones: '/funcion',
        registrarFila: '/fila',
        actualizarFilaById: (id: number) => `/fila/${id}`,
        getAllFilas: '/fila',
        registrarButaca: '/butaca',
        actualizarButacaById: (id: number) => `/butaca/${id}`,
        getAllButacas: '/butaca',
    },
    MSVentasUrls: {
        baseUrl: 'http://localhost:3003',
        iniciarProcesoPago: '/ventas/proceso-pago',
    },
    MSPromocionesUrls: {
        baseUrl: 'http://localhost:3004',
    },
};
